# Generated by Django 4.1.1 on 2022-10-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Secton',
            new_name='Section',
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'Secciones'},
        ),
    ]
